spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        names-in:
          destination: names
          contentType: application/json
        names-out:
          destination: names
          contentType: application/json